# Generated by Django 3.0.4 on 2020-03-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='latitude',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longitude',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
