# Generated by Django 3.0.4 on 2020-03-14 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_description', models.TextField(max_length=5000)),
                ('shop_front_image', models.ImageField(upload_to=shops.models.upload_location)),
                ('shop_created', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('shop_updated', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shops Data',
            },
        ),
    ]
